name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Restore dependencies
      run: dotnet restore src
    - name: Build DotLiquid
      run: dotnet build --no-restore src/DotLiquid --configuration Release --framework netstandard1.3
    - name: Build DotLiquid.Tests
      run: dotnet build --no-restore src/DotLiquid.Tests --configuration Release --framework netcoreapp1.0
    - name: Test DotLiquid
      run: dotnet test --no-build --verbosity normal src/DotLiquid.Tests/DotLiquid.Tests.csproj --framework netcoreapp1.0 --filter "TestCategory!=windows"
