name: dotnet-core

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/*.md'
      - '**/*.markdown'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**/*.md'
      - '**/*.markdown'
      - '**/*.gitignore'
      - '**/*.gitattributes'

env:
  config: Release

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'

    - name: Restore dependencies
      run: dotnet restore src

    - name: Build DotLiquid
      run: dotnet build --no-restore src/DotLiquid --configuration ${{ env.config }} --framework netstandard1.3

    - name: Build DotLiquid.Tests
      run: dotnet build --no-restore src/DotLiquid.Tests --configuration ${{ env.config }} --framework netcoreapp1.0

    - name: Test DotLiquid
      run: dotnet test src/DotLiquid.Tests/DotLiquid.Tests.csproj --no-restore --no-build --verbosity normal --configuration Debug --framework netcoreapp1.0 --filter "TestCategory!=windows"
