name: dotnet-core

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/*.md'
      - '**/*.markdown'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**/*.md'
      - '**/*.markdown'
      - '**/*.gitignore'
      - '**/*.gitattributes'

env:
  config: Release

jobs:
  build:

    runs-on: ubuntu-16.04 #ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 1.0.4 #'3.1.202'

    - name: Dotnet info
      run: dotnet --info

    - name: Restore dependencies
      run: dotnet restore src

    - name: Build DotLiquid
      run: dotnet build src/DotLiquid --no-restore --configuration ${{ env.config }} --framework netstandard1.3

    - name: Build DotLiquid.Tests
      run: dotnet build src/DotLiquid.Tests --no-restore --configuration ${{ env.config }} --framework netcoreapp1.0

    - name: Environment Printer
      uses: managedkaos/print-env@v1.0
  
    - name: List Tests
      run: dotnet test -t src/DotLiquid.Tests --no-build --verbosity normal --configuration Debug --framework netcoreapp1.0 --filter "TestCategory!=windows"

    - name: Test DotLiquid
      run: dotnet test src/DotLiquid.Tests --no-build --verbosity normal --configuration Debug --framework netcoreapp1.0 --filter "TestCategory!=windows"
